version: '3.8'

services:
  # ==========================================
  # LONG-RUNNING SERVICES (The Web Application)
  # ==========================================

  # 1. The Front Door (Web Server)
  nginx:
    image: nginx:alpine # Use the official Nginx image
    ports:
      - "8000:80" # Map port 8000 of the host to port 80 of the container
    volumes:
      - ./src:/var/www/html # Map the src directory (our Laravel app) to the /var/www/html directory inside the container
      - ./nginx.conf:/etc/nginx/conf.d/default.conf # Map the nginx.conf file to the /etc/nginx/conf.d/default.conf file inside the container
    depends_on:
      - php

  # 2. The Engine (Executes PHP code)
  php:
    build:
      context: .
      dockerfile: dockerfiles/php.Dockerfile
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql

  # 3. The Memory (Database)
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    env_file:
      - ./env/mysql.env # Use the .env file to set environment variables like database credentials and root password 
    volumes:
      - dbdata:/var/lib/mysql

  # ==========================================
  # UTILITY CONTAINERS (Run once, then die)
  # ==========================================

  # 4. Package Manager (Like npm)
  composer:
    build:
      context: .
      dockerfile: dockerfiles/composer.Dockerfile
    profiles:
      - cli # Only run this container when we explicitly ask for it
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html

  # 5. Laravel CLI (Like nest CLI)
  artisan:
    build:
      context: .
      dockerfile: dockerfiles/php.Dockerfile
    profiles:
      - cli # Only run this container when we explicitly ask for it
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    entrypoint: [ "php", "artisan" ]
    depends_on:
      - mysql

volumes:
  dbdata:
