apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: user-api-deployment
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app: user-api-pod
  template: 
    metadata: 
      labels: 
        app: user-api-pod
    spec: 
      containers: 
        - name: user-api-container 
          image: user-image 
          imagePullPolicy: Never 
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: user-api-service
spec:
  selector:
    app: user-api-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
        