apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: auth-api-deployment
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app: auth-api-pod
  template: 
    metadata: 
      labels: 
        app: auth-api-pod
    spec: 
      containers: 
        - name: auth-api-container 
          image: auth-image 
          imagePullPolicy: Never 
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  selector:
    app: auth-api-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
        