apiVersion: apps/v1 # api version
kind: Deployment # type of resource
metadata: # metadata of the resource
  name: first-app-deployment
spec: # spec of the resource
  replicas: 3 # number of replicas
  selector: # it knows which pods to manage
    matchLabels: # can put more labels here e.g. app: first-app-pod, version: v1
      app: first-app-pod
  template: # template of the resource
    metadata: # metadata of the template
      labels: # labels of the template
        app: first-app-pod
    spec: # spec of the template
      containers: # containers of the template
        - name: first-app-container # name of the container
          image: kub-first-image # image of the container
          imagePullPolicy: Never # image pull policy
          #livenessProbe: # it checks if the container is alive
            #httpGet: 
              #path: / # path of the request
              #port: 8080 # path of the app
            #initialDelaySeconds: 10 # delay before the first check
            #periodSeconds: 10 # interval between checks
            #timeoutSeconds: 2 # timeout for the request
            #failureThreshold: 3 # number of failures before the container is restarted
            #successThreshold: 1 # number of successes before the container is restarted
            